# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Yarn@3
  inputs:
    projectDirectory: './'
    arguments: 'install'

- script: |
    yarn run build
  displayName: 'Parcel Build'

- task: PowerShell@2
  displayName: 'Deploy to Firebase'
  inputs:
    targetType: 'inline'
    script: |
      npm i -g firebase-tools
      write-host "starting deploy...";
      firebase --version;
      firebase login --token $fireBaseToken;
      firebase use --token $fireBaseToken --add $fireBaseProject;
      firebase deploy --message "Release: $releaseMessage" --token $fireBaseToken;
      write-host "deployment completed";
      
      Pop-Location